# Generated by Django 2.0.4 on 2018-04-19 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20180419_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='avatar',
            field=models.URLField(max_length=1000),
        ),
    ]
